added 1 bit Format Mono LSB support
rr-/ida-images pull request #9
Opened 2018-10-18 00:06 UTC by ValkA

I think I could use QImage::Format_Mono flag, but it wasn't working for me, so I wrote a code that converts it to Grayscale8.

2018-10-18 05:34 UTC, rr- requested changes
Cosmetic changes only.
It would be great to offer faster alternative if numpy is available similar to how brightness adjustment looks like, but it's not a requirement.

I'll take a look if I can get it to work with Qt's mono pixel format later, for now we'll merge it like this (after the formatting changes).

2018-10-18 05:34 UTC, rr- commented on librgb/pixel_formats.py
> +        (GRAY1, '1:Image1Bit (1)', 'G1'),
```suggestion
        (GRAY1, '1:Binary (1)', 'G1'),
```

2018-10-18 05:34 UTC, rr- commented on librgb/renderer.py
> +            data_size = data_size / 8
```suggestion
            data_size /= 8
```

2018-10-18 05:34 UTC, rr- commented on librgb/renderer.py
> +                data = data + ''.join(''.join(chr(((ord(byte)&(1<<bit))>>bit)*255) for byte in old_data[:stride]) for bit in range(8))
```suggestion
                data += ''.join(
                    ''.join(
                        chr(((ord(byte) & (1 << bit)) >> bit) * 255)
                        for byte in old_data[:stride]
                    )
                    for bit in range(8)
                )
```

2018-10-18 05:56 UTC, ValkA commented
Have you tested it? I think python doesn't support += and /=. Anyway, if it works I don't care

2018-10-18 05:59 UTC, rr- commented
>Have you tested it? I think python doesn't support += and /=.

…
Yes, it does.
https://docs.python.org/3/reference/grammar.html `augassign`

2018-10-18 06:07 UTC, rr- commented
It doesn't work for me…

1. Data size not divisible by 8 lead to a crash
2. ```
  File "/home/rr-/src/maintained/ida-images/librgb/renderer.py", line 71, in <genexpr>
    for bit in range(8)
  File "/home/rr-/src/maintained/ida-images/librgb/renderer.py", line 69, in <genexpr>
    for byte in old_data[:stride]
TypeError: ord() expected string of length 1, but int found
```

I'll try to fix the issue within this PR.

2018-10-18 06:30 UTC, rr- commented
LMK if this works for you.

2018-10-23 13:20 UTC, rr- commented
I'm assuming yes.

2018-10-23 13:21 UTC, merged